### ISSUE TITLE
Deno binary download issue

### ISSUE THREAD

**Issue by louis-bompart** [netlify/edge-bundler#6]
## Describe the bug

When deno is not installed globally, `edge-bundler` download it and then and try to run `deno --version` (using the downloaded version).
However, `edge-bundler` does not wait for the binary to be 'free' by the operating system, which can lead to EBUSY[^1] error.

## Configuration

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 21.94 GB / 31.91 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.6.0 - ~\AppData\Roaming\npm\npm.CMD
```

## Pull requests
🔜 

[^1]: https://nodejs.org/dist/latest-v16.x/docs/api/all.html#all_os_posix-error-constants

**Comment by louis-bompart** [comment]
Issue is reproducible in CI, https://github.com/louis-bompart/edge-bundler/runs/6084634765?check_suite_focus=true
(I just skipped the `lint` 'cause it seems to be broken on main too)

**Comment by minivan** [comment]
hi @louis-bompart ! this should be fixed in the newest release of the edge bundler, can you try and see if it works for you? Thank you!

**Comment by jackiewmacharia** [comment]
Closing this. In case of additional issues, let us know in subsequent comments and we'll get to it.

**Comment by louis-bompart** [comment]
Hi, sorry for the late answer, I just tested the latest release, I can confirm that the issue has been mitigated ✅ thanks!
